[package]
name = "viceroy"
description = "Viceroy is a local testing daemon for Compute@Edge."
version = "0.2.10"
authors = ["Fastly"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"

[[bin]]
name = "viceroy"
path = "src/main.rs"

[dependencies]
itertools = "0.10.0"
structopt = "0.3.21"
tokio = {version = "1.2", features = ["full"]}
viceroy-lib = {path = "../lib", version = "^0.2.3"}
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
tracing-futures = "0.2.5"
hyper = {version = "0.14.0", features = ["full"]}
wat = "1.0.38"
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.66"
dap_types = { path = "../dap_types" }

[dev-dependencies]
anyhow = "1.0.31"
futures = "0.3"
url = "2.2"
